Fix completion source crash in Windows OS
Since source was added in completion, completion doesn't work on Windows OS because of use of Path.getPaths to retreive the file name.

For instance: here the error on Window OS

```
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/C:/Users/azerr/.lsp4xml/cache/https/www.w3.org/1999/11/xslt10.xsd
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
```

This PR fixes this bug on Wondows OS by avoiding using Paths.getPath to retrieve the file name.  I have too cleaned a little the code of generateDocumentation.